[package]
name = "play-game"
version = "0.1.0"
authors = ["thebarbershopper <cld251@gmail.com>"]

[dependencies]
nim = { path = "../nim" }
agricola = { path = "../agricola" }
boardgameai-rs = { path = "../../../boardgameai-rs" }
rand = "*"
lazy_static = "1.0"
colored = "1.6"
